# Generated by Django 2.1.5 on 2019-01-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherforecast', '0002_auto_20190119_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='forecastDate',
            field=models.DateField(default='2019-01-19'),
        ),
    ]
