# Generated by Django 2.1.5 on 2019-01-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherforecast', '0003_weatherforecast_forecastdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherActualMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('time', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('weatherCondition', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='autoForecastRate',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='manualForecastRate',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='weatherforecastdayhour',
            name='autoForecastRate',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='weatherforecastdayhour',
            name='manualForecastRate',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='forecastDate',
            field=models.DateField(default='2019-01-22'),
        ),
    ]
