# Generated by Django 2.1.5 on 2019-01-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherforecast', '0004_auto_20190122_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='forecastDate',
            field=models.DateField(default='2019-01-29'),
        ),
    ]
