# Generated by Django 2.1.7 on 2019-02-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherforecast', '0008_auto_20190225_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='forecastDate',
            field=models.DateField(default='2019-02-26'),
        ),
    ]
