# Generated by Django 2.1.7 on 2019-03-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherforecast', '0009_auto_20190226_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='forecastDate',
            field=models.DateField(default='2019-03-01'),
        ),
    ]
