# Generated by Django 2.1.5 on 2019-01-29 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdevice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartFunctionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configValue', models.CharField(max_length=100)),
                ('smartFunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartdevice.SmartFunction')),
            ],
        ),
        migrations.CreateModel(
            name='SmartFunctionParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartFunctionParam', models.CharField(max_length=100)),
                ('smartFunctionParamMeta', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='smartdevice',
            name='functions',
        ),
        migrations.AddField(
            model_name='smartdevice',
            name='functions',
            field=models.ManyToManyField(to='smartdevice.SmartFunction'),
        ),
        migrations.AddField(
            model_name='smartfunctionconfig',
            name='smartFunctionParameter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartdevice.SmartFunctionParameter'),
        ),
    ]
