# Generated by Django 2.1.5 on 2019-01-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdevice', '0002_auto_20190129_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartfunctionparameter',
            old_name='smartFunctionParam',
            new_name='smartFunctionParamDescription',
        ),
        migrations.AddField(
            model_name='smartdevice',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartfunction',
            name='code',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartfunctionparameter',
            name='smartFunctionParamCode',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
    ]
