# Generated by Django 2.1.5 on 2019-02-01 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdevice', '0003_auto_20190129_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartFunctionUnstructuredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartDeviceDataKey', models.CharField(max_length=50)),
                ('smartDeviceDataValue', models.CharField(max_length=255)),
                ('smartFunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartdevice.SmartDevice')),
            ],
        ),
    ]
