# Generated by Django 2.1.5 on 2019-02-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdevice', '0004_smartfunctionunstructureddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartdevice',
            name='code',
            field=models.CharField(default='-', max_length=6),
            preserve_default=False,
        ),
    ]
