# Generated by Django 2.1.5 on 2019-02-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdevice', '0006_auto_20190201_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartfunctionunstructureddata',
            name='description',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
