# Generated by Django 2.1.5 on 2019-02-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdevice', '0007_smartfunctionunstructureddata_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartfunctionunstructureddata',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
