# Generated by Django 2.1.5 on 2019-02-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdevice', '0008_auto_20190201_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartfunctionunstructureddata',
            old_name='smartFunction',
            new_name='smartDevice',
        ),
        migrations.RenameField(
            model_name='smartfunctionunstructureddata',
            old_name='description',
            new_name='smartDeviceDataDescription',
        ),
    ]
