# Generated by Django 2.1.3 on 2018-12-21 22:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeUnit', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('energyProduction', models.PositiveIntegerField(default=0)),
                ('energyConsumtion', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SolarModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solModuleType', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiSiteId', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='solarmodule',
            name='solSystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.SolarSystem'),
        ),
        migrations.AddField(
            model_name='solarmeasurement',
            name='solModule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.SolarModule'),
        ),
    ]
