# Generated by Django 2.1.3 on 2018-12-25 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarLiveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeUnit', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('energyProduction', models.PositiveIntegerField(default=0)),
                ('energyConsumtion', models.PositiveIntegerField(default=0)),
                ('solModule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.SolarModule')),
            ],
        ),
        migrations.AlterField(
            model_name='solarmeasurement',
            name='solModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.SolarModule'),
        ),
    ]
