# Generated by Django 2.1.3 on 2018-12-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20181225_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarmeasurement',
            name='energyConsumtion',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='solarmeasurement',
            name='energyProduction',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
