# Generated by Django 2.1.5 on 2019-01-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_auto_20181228_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('wattHours', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='solarlivedata',
            name='solModule',
        ),
        migrations.DeleteModel(
            name='SolarLiveData',
        ),
    ]
