# Generated by Django 2.1.5 on 2019-01-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_auto_20190116_2154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
