# Generated by Django 2.1.5 on 2019-01-19 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarmeasurement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 22, 15, 25, 719730)),
        ),
    ]
