# Generated by Django 2.1.5 on 2019-01-19 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_auto_20190119_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarmeasurement',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
