# Generated by Django 2.1.7 on 2019-02-25 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_auto_20190222_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarMeasurement_power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeUnit', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('powerProduction', models.FloatField(blank=True, default=None, null=True)),
                ('powerConsumtion', models.FloatField(blank=True, default=None, null=True)),
                ('solModule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.SolarModule')),
            ],
        ),
    ]
