# Generated by Django 2.1.7 on 2019-02-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0013_solarmeasurement_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarmeasurement_power',
            name='powerGrid',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
