# Generated by Django 2.1.7 on 2019-03-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0015_generalconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalconfig',
            old_name='generalValue',
            new_name='generalConfigValue',
        ),
    ]
